auth:
  username: vagrant
  password: vagrant
persistence:
  enabled: true
  existingClaim: nfs-pvc
service:
  type: ClusterIP
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: rabbitmq.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []
