alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    existingClaim: nfs-pvc
server:
  persistentVolume:
    enabled: true
    existingClaim: nfs-pvc
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.local
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls: []
pushgateway:
  enabled: true
  persistentVolume:
    enabled: true
    existingClaim: nfs-pvc
