apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    env: production
    tier: database
    app: mysql
    name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/k8s/mysql
    server:  192.168.56.40
