apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  labels:
    env: production
    tier: backend
    app: pvc
    name: backend-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/k8s/backend
    server:  192.168.56.40
