apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32004
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32444
