zookeeper:
  enabled: true
  persistence:
    enabled: true
    existingClaim: nfs-pvc
replicaCount: 1
persistence:
  enabled: true
  existingClaim: nfs-pvc
service:
  type: ClusterIP
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi
externalAccess:
  enabled: true
  service:
    type: ClusterIP
auth:
  enabled: true
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: true
    mechanisms: plain
    username: vagrant
    password: vagrant
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: kafka.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []
