replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - k8sgpt.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []
auth:
  username: vagrant
  password: vagrant
