apiVersion: v1
kind: Service
metadata:
  name: kyverno-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kyverno
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 32011
