replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
webhooks:
  enabled: true
backgroundController:
  enabled: true
# 샘플 정책 적용 예시(별도 yaml로 관리 권장)
# policies:
#   - name: require-labels
#     rules:
#       - name: check-for-labels
#         match:
#           resources:
#             kinds:
#               - Pod
#         validate:
#           message: "모든 파드에 'app' 라벨이 필요합니다."
#           pattern:
#             metadata:
#               labels:
#                 app: "*"
