apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argo-rollouts
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 32012
