apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- admin/service.yaml 
- admin/ingress/ingress.yaml 
- admin/deployment.yaml
- admin/autoscaler.yaml


images:
- name: egovframe/egovframe-msa-edu-frontend-admin:latest
  # newName: foobar/egovframe-msa-edu-frontend-admin
  newTag: latest
- name: egovframe/egovframe-msa-edu-frontend-portal:latest
  # newName: foobar/egovframe-msa-edu-frontend-portal
  newTag: latest


patches:
- target:
    name: frontend-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "portal.localhost"
- target:
    name: frontend-admin-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "admin.localhost"
