apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32443
