controller:
  replicaCount: 2
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  admissionWebhooks:
    enabled: true
  metrics:
    enabled: true
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # 로그/임시파일 등 필요시 NFS PVC 마운트 예시
  # extraVolumeMounts:
  #   - name: nfs-pvc
  #     mountPath: /data
  # extraVolumes:
  #   - name: nfs-pvc
  #     persistentVolumeClaim:
  #       claimName: nfs-pvc
